### ISSUE TITLE
Extra spacing on last example on "How to support Images with unknown Dimensions?"

### ISSUE THREAD

**Issue by andrewspy** [ampproject/amp-by-example#1017]
In the example "How_to_support_Images_with_unknown_Dimensions?", if you set the following CSS:-

```css
<style amp-custom>
  amp-carousel {
    background: red;
  }
</style>
```

You will see extra unnecessary spacing on the last example on "Image Carousels"

**Comment by sebastianbenz** [comment]
I can't reproduce this, which browser are you using? Can you also post a screenshot. Thanks!

**Comment by andrewspy** [comment]
You may reproduce by using the code in [AMP Playground](https://ampbyexample.com/playground/#url=https%3A%2F%2Fampbyexample.com%2Fadvanced%2Fhow_to_support_images_with_unknown_dimensions%2Fsource%2F), by adding the following CSS:-

```css
<style amp-custom>
  amp-carousel {
    background: red;
  }
</style>
```

I am having issue on the following broswer:-

- [x] Chrome Version 62.0.3202.94 (Official Build) (64-bit)
- [x] Firefox 57.0 (64-bit)
- [x] Microsoft Edge

And below is the screenshot:-
![image](https://user-images.githubusercontent.com/3106425/33152221-8d1e11c8-d016-11e7-826a-a6d3102421dc.png)
